name: Test

on: [push]

jobs:
  BuildOmp:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: Jimver/cuda-toolkit@v0.2.15
      id: cuda-toolkit
      with:
        cuda: '12.3.0'
        method: 'network'
        sub-packages: '["nvcc", "thrust"]'
    - run: sudo apt install -y cmake build-essential g++
    - run: cmake .
    - run: make omp_tests

  BuildCuda:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: Jimver/cuda-toolkit@v0.2.15
      id: cuda-toolkit
      with:
        cuda: '12.3.0'
        method: 'network'
        sub-packages: '["nvcc", "thrust"]'
    - run: sudo apt install -y cmake build-essential g++
    - run: cmake .
    - run: make cuda_tests

  RunTests:
    needs: [BuildOmp, BuildCuda]

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: Jimver/cuda-toolkit@v0.2.15
      id: cuda-toolkit
      with:
        cuda: '12.3.0'
        method: 'network'
        sub-packages: '["nvcc", "thrust"]'

    - run: sudo apt install -y cmake build-essential g++
    - run: cmake .
    - run: make omp_tests
    - run: ./omp_tests

  
