name: Test

on: [push]

jobs:
  Install:
    runs-on: ubuntu-22.04

    steps:
    - uses: Jimver/cuda-toolkit@v0.2.15
      id: cuda-toolkit
      with:
        cuda: '12.4.1'
        method: 'network'
        sub-packages: '["nvcc", "thrust"]'

    - run: nvcc -V

  Build:
    needs: Install
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - run: nvcc -V
    - run: ls
    - run: sudo apt install -y cmake build-essential g++
    - run: mkdir build && cd build
    - run: cmake ..
    - run: make

  
