name: Test

on: [push]

jobs:
  Install:
    runs-on: ubuntu-latest

    steps:
    - uses: Jimver/cuda-toolkit@v0.2.15
      id: cuda-toolkit
      with:
        cuda: '12.4.1'

    - run: echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"

    - run: echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"

    - run: nvcc -V